# Generated by Django 3.2.10 on 2022-01-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='polygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notam', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Marker',
        ),
    ]
